# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: web/
repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.13
    hooks:
    - id: mdformat
      args: ['--number', '--wrap=79']
      additional_dependencies:
      - mdformat-toc==0.3.0
